import type { ComponentInput } from './schema.ts'

const CHECKED = '2026-09-11'
const ada = (sku: string) => ({ partner: 'adafruit' as const, sku, url: `https://www.adafruit.com/product/${sku}` })
const rpi = (slug: string, sku: string) => ({ partner: 'raspberrypi' as const, sku, url: `https://www.raspberrypi.com/products/${slug}/` })
const ard = (slug: string, sku: string) => ({ partner: 'arduino' as const, sku, url: `https://store.arduino.cc/products/${slug}` })
const generic = (sku: string) => ({ partner: 'generic' as const, sku, url: 'https://www.adafruit.com/category/17' })

/**
 * Seeded partner index. Adafruit prices and stock were read from the public
 * Adafruit product API on CHECKED and can be refreshed live. Raspberry Pi
 * prices are published recommended retail prices. Arduino prices are store
 * estimates. Nothing here is a supplier quote.
 */
export const seedComponents: ComponentInput[] = [
  // ───────────────────────── Controllers ─────────────────────────
  {
    id: 'pico2w', name: 'Raspberry Pi Pico 2 W', category: 'Controller',
    spec: 'RP2350 · Wi-Fi + BLE · 3.3 V logic · 26 GPIO · micro-USB',
    notes: 'Default controller for battery-friendly connected gadgets. Programs in MicroPython over USB with no toolchain.',
    source: rpi('raspberry-pi-pico-2', 'SC1634'), alsoFrom: [ada('6087')],
    datasheet: 'https://datasheets.raspberrypi.com/picow/pico-2-w-datasheet.pdf',
    price: 7, pricing: 'msrp', priceCheckedAt: CHECKED, stock: 'unknown',
    provides: ['mcu', 'connect:wifi', 'connect:ble', 'connect:usb'],
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 51, d: 21, h: 5 },
    controller: {
      platform: 'micropython', logicVoltage: '3v3', gpio: 26,
      buses: ['i2c', 'spi', 'uart', 'onewire', 'pwm', 'adc', 'gpio', 'usb'],
      pinPool: ['GP2', 'GP3', 'GP6', 'GP7', 'GP8', 'GP9', 'GP10', 'GP11', 'GP12', 'GP13', 'GP14', 'GP15', 'GP16', 'GP17', 'GP18', 'GP19', 'GP20', 'GP21', 'GP22', 'GP26', 'GP27', 'GP28'],
      busPins: { i2c: { SDA: 'GP4', SCL: 'GP5' }, spi: { SCK: 'GP18', MOSI: 'GP19', MISO: 'GP16' }, uart: { TX: 'GP0', RX: 'GP1' }, adc: { A0: 'GP26', A1: 'GP27', A2: 'GP28' } },
      wifi: true, ble: true, suppliesRails: ['3v3', '5v'],
    },
    code: { micropython: { libraries: [], setup: 'from machine import Pin, I2C, PWM, ADC\nimport time\ni2c = I2C(0, sda=Pin(4), scl=Pin(5), freq=400_000)', loop: '' } },
    tags: ['wifi', 'micropython', 'low-power'],
  },
  {
    id: 'picow', name: 'Raspberry Pi Pico W', category: 'Controller',
    spec: 'RP2040 · Wi-Fi · 3.3 V logic · 26 GPIO · micro-USB',
    notes: 'Previous generation Pico with Wi-Fi. Same pinout as Pico 2 W; use when the 2 W is out of stock.',
    source: rpi('raspberry-pi-pico', 'SC0918'), alsoFrom: [ada('5526')],
    price: 6, pricing: 'msrp', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['mcu', 'connect:wifi', 'connect:usb'],
    footprint: { w: 51, d: 21, h: 5 },
    controller: {
      platform: 'micropython', logicVoltage: '3v3', gpio: 26,
      buses: ['i2c', 'spi', 'uart', 'onewire', 'pwm', 'adc', 'gpio', 'usb'],
      pinPool: ['GP2', 'GP3', 'GP6', 'GP7', 'GP8', 'GP9', 'GP10', 'GP11', 'GP12', 'GP13', 'GP14', 'GP15', 'GP16', 'GP17', 'GP18', 'GP19', 'GP20', 'GP21', 'GP22', 'GP26', 'GP27', 'GP28'],
      busPins: { i2c: { SDA: 'GP4', SCL: 'GP5' }, spi: { SCK: 'GP18', MOSI: 'GP19', MISO: 'GP16' }, uart: { TX: 'GP0', RX: 'GP1' }, adc: { A0: 'GP26', A1: 'GP27', A2: 'GP28' } },
      wifi: true, ble: false, suppliesRails: ['3v3', '5v'],
    },
    code: { micropython: { libraries: [], setup: 'from machine import Pin, I2C, PWM, ADC\nimport time\ni2c = I2C(0, sda=Pin(4), scl=Pin(5), freq=400_000)', loop: '' } },
    tags: ['wifi', 'micropython'],
  },
  {
    id: 'esp32s3-feather', name: 'Adafruit ESP32-S3 Feather', category: 'Controller',
    spec: 'ESP32-S3 · Wi-Fi + BLE · 3.3 V logic · STEMMA QT · LiPo charger on board',
    notes: 'Best pick when the device runs from a LiPo battery: charging and battery monitoring are built in. Arduino or MicroPython.',
    source: ada('5323'), alsoFrom: [ada('5477')],
    price: 17.5, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['mcu', 'connect:wifi', 'connect:ble', 'connect:usb', 'power:charger'],
    footprint: { w: 51, d: 23, h: 8 },
    controller: {
      platform: 'micropython', logicVoltage: '3v3', gpio: 21,
      buses: ['i2c', 'spi', 'uart', 'onewire', 'pwm', 'adc', 'gpio', 'usb'],
      pinPool: ['GPIO5', 'GPIO6', 'GPIO9', 'GPIO10', 'GPIO11', 'GPIO12', 'GPIO13', 'GPIO18', 'GPIO17', 'GPIO16', 'GPIO15', 'GPIO14', 'GPIO8'],
      busPins: { i2c: { SDA: 'GPIO3', SCL: 'GPIO4' }, spi: { SCK: 'GPIO36', MOSI: 'GPIO35', MISO: 'GPIO37' }, uart: { TX: 'GPIO39', RX: 'GPIO38' }, adc: { A0: 'GPIO18', A1: 'GPIO17', A2: 'GPIO16' } },
      wifi: true, ble: true, suppliesRails: ['3v3'],
    },
    code: { micropython: { libraries: [], setup: 'from machine import Pin, I2C, PWM, ADC\nimport time\ni2c = I2C(0, sda=Pin(3), scl=Pin(4), freq=400_000)', loop: '' } },
    tags: ['wifi', 'battery', 'stemma-qt'],
  },
  {
    id: 'uno-r4-wifi', name: 'Arduino UNO R4 WiFi', category: 'Controller',
    spec: 'Renesas RA4M1 + ESP32-S3 radio · 5 V logic · 14 digital + 6 analog · 12×8 LED matrix',
    notes: 'Choose for 5 V sensors and the classic Arduino IDE workflow. Not battery friendly.',
    source: ard('uno-r4-wifi', 'ABX00087'),
    datasheet: 'https://docs.arduino.cc/resources/datasheets/ABX00087-datasheet.pdf',
    price: 27.5, pricing: 'estimate', priceCheckedAt: CHECKED, stock: 'unknown',
    provides: ['mcu', 'connect:wifi', 'connect:ble', 'connect:usb'],
    footprint: { w: 69, d: 54, h: 15 },
    controller: {
      platform: 'arduino', logicVoltage: '5v', gpio: 20,
      buses: ['i2c', 'spi', 'uart', 'onewire', 'pwm', 'adc', 'gpio', 'usb'],
      pinPool: ['D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'A0', 'A1', 'A2', 'A3'],
      busPins: { i2c: { SDA: 'SDA', SCL: 'SCL' }, spi: { SCK: 'D13', MOSI: 'D11', MISO: 'D12' }, uart: { TX: 'D1', RX: 'D0' }, adc: { A0: 'A0', A1: 'A1', A2: 'A2' } },
      wifi: true, ble: true, suppliesRails: ['3v3', '5v'],
    },
    code: { arduino: { libraries: [], setup: '#include <Wire.h>\n', loop: '' } },
    tags: ['arduino', '5v', 'wifi'],
  },
  {
    id: 'nano-esp32', name: 'Arduino Nano ESP32', category: 'Controller',
    spec: 'ESP32-S3 · Wi-Fi + BLE · 3.3 V logic · Nano footprint · USB-C',
    notes: 'Small Arduino-branded ESP32. Works with Arduino IDE or MicroPython.',
    source: ard('nano-esp32', 'ABX00083'),
    price: 21, pricing: 'estimate', priceCheckedAt: CHECKED, stock: 'unknown',
    provides: ['mcu', 'connect:wifi', 'connect:ble', 'connect:usb'],
    footprint: { w: 45, d: 18, h: 8 },
    controller: {
      platform: 'arduino', logicVoltage: '3v3', gpio: 22,
      buses: ['i2c', 'spi', 'uart', 'onewire', 'pwm', 'adc', 'gpio', 'usb'],
      pinPool: ['D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'A0', 'A1', 'A2', 'A3', 'A6', 'A7'],
      busPins: { i2c: { SDA: 'A4', SCL: 'A5' }, spi: { SCK: 'D13', MOSI: 'D11', MISO: 'D12' }, uart: { TX: 'D1', RX: 'D0' }, adc: { A0: 'A0', A1: 'A1', A2: 'A2' } },
      wifi: true, ble: true, suppliesRails: ['3v3'],
    },
    code: { arduino: { libraries: [], setup: '#include <Wire.h>\n', loop: '' } },
    tags: ['arduino', 'wifi', 'compact'],
  },
  {
    id: 'pi5', name: 'Raspberry Pi 5 (4 GB)', category: 'Controller',
    spec: 'Quad-core ARM Linux · 40-pin GPIO · Gigabit Ethernet · Wi-Fi + BLE · CSI camera',
    notes: 'Use when the device needs a camera, a web dashboard, or a database. Needs a 27 W USB-C supply and microSD card.',
    source: rpi('raspberry-pi-5', 'SC1111'), alsoFrom: [ada('5813')],
    price: 60, pricing: 'msrp', priceCheckedAt: CHECKED, stock: 'unknown',
    provides: ['sbc', 'connect:wifi', 'connect:ble', 'connect:usb'],
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 85, d: 56, h: 18 },
    controller: {
      platform: 'python', logicVoltage: '3v3', gpio: 26,
      buses: ['i2c', 'spi', 'uart', 'onewire', 'pwm', 'gpio', 'usb', 'csi'],
      pinPool: ['GPIO17', 'GPIO27', 'GPIO22', 'GPIO23', 'GPIO24', 'GPIO25', 'GPIO5', 'GPIO6', 'GPIO12', 'GPIO13', 'GPIO16', 'GPIO26', 'GPIO20', 'GPIO21'],
      busPins: { i2c: { SDA: 'GPIO2', SCL: 'GPIO3' }, spi: { SCK: 'GPIO11', MOSI: 'GPIO10', MISO: 'GPIO9' }, uart: { TX: 'GPIO14', RX: 'GPIO15' }, onewire: { DQ: 'GPIO4' } },
      wifi: true, ble: true, suppliesRails: ['3v3', '5v'],
    },
    code: { python: { libraries: ['gpiozero', 'smbus2'], setup: 'from gpiozero import *\nimport time', loop: '' } },
    tags: ['linux', 'camera', 'python'],
  },
  {
    id: 'pizero2w', name: 'Raspberry Pi Zero 2 W', category: 'Controller',
    spec: 'Quad-core ARM Linux · 40-pin GPIO · Wi-Fi + BLE · CSI camera · 65 × 30 mm',
    notes: 'Smallest Linux option. Good for camera projects and Python. Header must be soldered or use the pre-headered variant.',
    source: rpi('raspberry-pi-zero-2-w', 'SC0510'), alsoFrom: [ada('5291'), ada('6008')],
    price: 15, pricing: 'msrp', priceCheckedAt: CHECKED, stock: 'unknown',
    provides: ['sbc', 'connect:wifi', 'connect:ble', 'connect:usb'],
    footprint: { w: 65, d: 30, h: 6 },
    controller: {
      platform: 'python', logicVoltage: '3v3', gpio: 26,
      buses: ['i2c', 'spi', 'uart', 'onewire', 'pwm', 'gpio', 'usb', 'csi'],
      pinPool: ['GPIO17', 'GPIO27', 'GPIO22', 'GPIO23', 'GPIO24', 'GPIO25', 'GPIO5', 'GPIO6', 'GPIO12', 'GPIO13', 'GPIO16', 'GPIO26', 'GPIO20', 'GPIO21'],
      busPins: { i2c: { SDA: 'GPIO2', SCL: 'GPIO3' }, spi: { SCK: 'GPIO11', MOSI: 'GPIO10', MISO: 'GPIO9' }, uart: { TX: 'GPIO14', RX: 'GPIO15' }, onewire: { DQ: 'GPIO4' } },
      wifi: true, ble: true, suppliesRails: ['3v3', '5v'],
    },
    code: { python: { libraries: ['gpiozero', 'smbus2'], setup: 'from gpiozero import *\nimport time', loop: '' } },
    tags: ['linux', 'camera', 'compact'],
  },

  {
    id: 'picam3', name: 'Raspberry Pi Camera Module 3', category: 'Sensor',
    spec: '12 MP · autofocus · CSI ribbon · 75° field of view',
    notes: 'Photos, time-lapse, and simple detection on a Raspberry Pi. Not usable on Pico or Arduino boards.',
    source: rpi('camera-module-3', 'SC0872'),
    price: 25, pricing: 'msrp', priceCheckedAt: CHECKED, stock: 'unknown',
    provides: ['sense:camera'],
    requires: { bus: 'csi', pins: 0, power: '3v3', currentMa: 250 },
    footprint: { w: 25, d: 24, h: 12 },
    code: { python: { libraries: ['picamera2'], setup: 'from picamera2 import Picamera2\ncamera = Picamera2()\ncamera.start()', loop: 'camera.capture_file("capture.jpg")' } },
    tags: ['camera', 'vision'],
  },

  // ───────────────────────── Sensors ─────────────────────────
  {
    id: 'bme280', name: 'BME280 temperature / humidity / pressure', category: 'Sensor',
    spec: 'I2C or SPI · 3.3–5 V · ±1 °C, ±3 % RH, ±1 hPa · STEMMA QT',
    notes: 'One board covers indoor climate, weather, and altitude. Mount away from the controller so its heat does not skew readings.',
    source: ada('2652'), price: 14.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:temperature', 'sense:humidity', 'sense:pressure'],
    requires: { bus: 'i2c', pins: 0, power: '3v3', currentMa: 1 },
    footprint: { w: 20, d: 18, h: 3 },
    code: {
      micropython: { libraries: ['bme280 (micropython-bme280)'], setup: 'import bme280\nclimate = bme280.BME280(i2c=i2c)', loop: 'temp_c, pressure_hpa, humidity = climate.values' },
      arduino: { libraries: ['Adafruit BME280 Library'], setup: '#include <Adafruit_BME280.h>\nAdafruit_BME280 climate;\nclimate.begin(0x77);', loop: 'float tempC = climate.readTemperature();\nfloat humidity = climate.readHumidity();' },
      python: { libraries: ['adafruit-circuitpython-bme280'], setup: 'import board, adafruit_bme280.basic as bme\nclimate = bme.Adafruit_BME280_I2C(board.I2C())', loop: 'temp_c, humidity = climate.temperature, climate.humidity' },
    },
    tags: ['climate', 'weather', 'i2c'],
  },
  {
    id: 'ds18b20', name: 'DS18B20 waterproof temperature probe', category: 'Sensor',
    spec: '1-Wire · 3.3–5 V · −55 to 125 °C · stainless probe on 1 m cable',
    notes: 'For liquids, soil, or anything you need to poke a probe into. Needs a 4.7 kΩ pull-up from data to 3.3 V.',
    source: ada('374'), price: 3.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:temperature'],
    requires: { bus: 'onewire', pins: 1, power: '3v3', currentMa: 2 },
    footprint: { w: 6, d: 50, h: 6, external: true },
    code: {
      micropython: { libraries: ['onewire', 'ds18x20'], setup: 'import onewire, ds18x20\nprobe_bus = ds18x20.DS18X20(onewire.OneWire(Pin(PROBE_PIN)))\nprobes = probe_bus.scan()', loop: 'probe_bus.convert_temp(); time.sleep_ms(750)\ntemp_c = probe_bus.read_temp(probes[0])' },
      arduino: { libraries: ['OneWire', 'DallasTemperature'], setup: '#include <OneWire.h>\n#include <DallasTemperature.h>\nOneWire oneWire(PROBE_PIN);\nDallasTemperature probe(&oneWire);\nprobe.begin();', loop: 'probe.requestTemperatures();\nfloat tempC = probe.getTempCByIndex(0);' },
      python: { libraries: ['w1thermsensor'], setup: 'from w1thermsensor import W1ThermSensor\nprobe = W1ThermSensor()', loop: 'temp_c = probe.get_temperature()' },
    },
    tags: ['liquid', 'probe', 'waterproof'],
  },
  {
    id: 'dht22', name: 'DHT22 temperature + humidity', category: 'Sensor',
    spec: 'Single-wire digital · 3.3–5 V · ±0.5 °C, ±2 % RH · 2 s update',
    notes: 'Cheap and common. Slow; read it no more than every two seconds. BME280 is more accurate if the budget allows.',
    source: ada('385'), price: 9.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'low',
    provides: ['sense:temperature', 'sense:humidity'],
    requires: { bus: 'gpio', pins: 1, power: '3v3', currentMa: 3 },
    footprint: { w: 15, d: 25, h: 8 },
    code: {
      micropython: { libraries: ['dht'], setup: 'import dht\nclimate = dht.DHT22(Pin(DHT_PIN))', loop: 'climate.measure()\ntemp_c, humidity = climate.temperature(), climate.humidity()' },
      arduino: { libraries: ['DHT sensor library'], setup: '#include <DHT.h>\nDHT climate(DHT_PIN, DHT22);\nclimate.begin();', loop: 'float tempC = climate.readTemperature();\nfloat humidity = climate.readHumidity();' },
    },
    tags: ['climate'],
  },
  {
    id: 'hc-sr04', name: 'HC-SR04 ultrasonic distance sensor', category: 'Sensor',
    spec: 'Trigger / echo · 5 V · 2–400 cm · 15° cone',
    notes: 'Echo pin is 5 V; on a 3.3 V controller use the included 10 kΩ divider. Struggles with soft or angled surfaces.',
    source: ada('3942'), price: 3.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:distance'],
    requires: { bus: 'gpio', pins: 2, power: '5v', currentMa: 15 },
    footprint: { w: 45, d: 20, h: 15 },
    code: {
      micropython: { libraries: ['hcsr04'], setup: 'from hcsr04 import HCSR04\nranger = HCSR04(trigger_pin=TRIG_PIN, echo_pin=ECHO_PIN)', loop: 'distance_cm = ranger.distance_cm()' },
      arduino: { libraries: ['NewPing'], setup: '#include <NewPing.h>\nNewPing ranger(TRIG_PIN, ECHO_PIN, 400);', loop: 'unsigned int distanceCm = ranger.ping_cm();' },
      python: { libraries: ['gpiozero'], setup: 'ranger = DistanceSensor(echo=ECHO_PIN, trigger=TRIG_PIN)', loop: 'distance_cm = ranger.distance * 100' },
    },
    tags: ['distance', 'parking', 'level'],
  },
  {
    id: 'vl53l0x', name: 'VL53L0X time-of-flight distance', category: 'Sensor',
    spec: 'I2C · 3.3–5 V · 30–1000 mm · laser ranging · STEMMA QT',
    notes: 'Precise short-range distance in a tiny package. Prefer over ultrasonic for anything under a metre or where the beam must be narrow.',
    source: ada('3317'), price: 14.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:distance'],
    requires: { bus: 'i2c', pins: 0, power: '3v3', currentMa: 20 },
    footprint: { w: 21, d: 18, h: 3 },
    code: {
      micropython: { libraries: ['vl53l0x'], setup: 'from vl53l0x import VL53L0X\nranger = VL53L0X(i2c)', loop: 'distance_mm = ranger.read()' },
      arduino: { libraries: ['Adafruit_VL53L0X'], setup: '#include <Adafruit_VL53L0X.h>\nAdafruit_VL53L0X ranger;\nranger.begin();', loop: 'VL53L0X_RangingMeasurementData_t m; ranger.rangingTest(&m);\nint distanceMm = m.RangeMilliMeter;' },
      python: { libraries: ['adafruit-circuitpython-vl53l0x'], setup: 'import board, adafruit_vl53l0x\nranger = adafruit_vl53l0x.VL53L0X(board.I2C())', loop: 'distance_mm = ranger.range' },
    },
    tags: ['distance', 'precise'],
  },
  {
    id: 'pir', name: 'PIR motion sensor', category: 'Sensor',
    spec: 'Digital output · 5 V supply, 3.3 V output · ~7 m range · adjustable hold time',
    notes: 'Detects warm bodies moving. Gives a simple on/off signal, so it is easy to wire and code. Not for pets under ~10 kg.',
    source: ada('189'), price: 9.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'low',
    provides: ['sense:motion'],
    requires: { bus: 'gpio', pins: 1, power: '5v', currentMa: 1 },
    footprint: { w: 32, d: 24, h: 25 },
    code: {
      micropython: { libraries: [], setup: 'motion = Pin(PIR_PIN, Pin.IN)', loop: 'motion_detected = motion.value() == 1' },
      arduino: { libraries: [], setup: 'pinMode(PIR_PIN, INPUT);', loop: 'bool motionDetected = digitalRead(PIR_PIN) == HIGH;' },
      python: { libraries: ['gpiozero'], setup: 'motion = MotionSensor(PIR_PIN)', loop: 'motion_detected = motion.motion_detected' },
    },
    tags: ['motion', 'presence', 'security'],
  },
  {
    id: 'bh1750', name: 'BH1750 ambient light sensor', category: 'Sensor',
    spec: 'I2C · 3.3–5 V · 1–65535 lux · STEMMA QT',
    notes: 'Reads brightness in lux. Good for auto-dimming lamps, grow-light control, and daylight logging.',
    source: ada('4681'), price: 4.5, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:light'],
    requires: { bus: 'i2c', pins: 0, power: '3v3', currentMa: 1 },
    footprint: { w: 25, d: 18, h: 3 },
    code: {
      micropython: { libraries: ['bh1750'], setup: 'from bh1750 import BH1750\nlight = BH1750(0x23, i2c)', loop: 'lux = light.measurement' },
      arduino: { libraries: ['BH1750'], setup: '#include <BH1750.h>\nBH1750 light;\nlight.begin();', loop: 'float lux = light.readLightLevel();' },
      python: { libraries: ['adafruit-circuitpython-bh1750'], setup: 'import board, adafruit_bh1750\nlight = adafruit_bh1750.BH1750(board.I2C())', loop: 'lux = light.lux' },
    },
    tags: ['light', 'lux'],
  },
  {
    id: 'mpu6050', name: 'MPU-6050 accelerometer + gyro', category: 'Sensor',
    spec: 'I2C · 3.3–5 V · 6-axis · STEMMA QT',
    notes: 'Detects tilt, shake, vibration, and orientation. Use for fall detection, vibration logging, or a level.',
    source: ada('3886'), price: 12.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:imu'],
    requires: { bus: 'i2c', pins: 0, power: '3v3', currentMa: 4 },
    footprint: { w: 26, d: 18, h: 3 },
    code: {
      micropython: { libraries: ['mpu6050'], setup: 'from mpu6050 import MPU6050\nimu = MPU6050(i2c)', loop: 'ax, ay, az = imu.acceleration' },
      arduino: { libraries: ['Adafruit MPU6050'], setup: '#include <Adafruit_MPU6050.h>\nAdafruit_MPU6050 imu;\nimu.begin();', loop: 'sensors_event_t a, g, t; imu.getEvent(&a, &g, &t);' },
      python: { libraries: ['adafruit-circuitpython-mpu6050'], setup: 'import board, adafruit_mpu6050\nimu = adafruit_mpu6050.MPU6050(board.I2C())', loop: 'ax, ay, az = imu.acceleration' },
    },
    tags: ['tilt', 'vibration', 'orientation'],
  },
  {
    id: 'ina219', name: 'INA219 current + voltage sensor', category: 'Sensor',
    spec: 'I2C · high-side · up to 26 V, ±3.2 A · 0.8 mA resolution',
    notes: 'Measures how much current a load draws. Useful for battery monitors, power loggers, and detecting a stalled motor.',
    source: ada('904'), price: 9.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:current'],
    requires: { bus: 'i2c', pins: 0, power: '3v3', currentMa: 1 },
    footprint: { w: 26, d: 21, h: 3 },
    code: {
      micropython: { libraries: ['ina219'], setup: 'from ina219 import INA219\npower_meter = INA219(0.1, i2c)\npower_meter.configure()', loop: 'current_ma = power_meter.current()\nbus_v = power_meter.voltage()' },
      arduino: { libraries: ['Adafruit INA219'], setup: '#include <Adafruit_INA219.h>\nAdafruit_INA219 powerMeter;\npowerMeter.begin();', loop: 'float currentMa = powerMeter.getCurrent_mA();' },
      python: { libraries: ['adafruit-circuitpython-ina219'], setup: 'import board, adafruit_ina219\npower_meter = adafruit_ina219.INA219(board.I2C())', loop: 'current_ma = power_meter.current' },
    },
    tags: ['power', 'current'],
  },
  {
    id: 'soil-stemma', name: 'Capacitive soil moisture sensor', category: 'Sensor',
    spec: 'I2C · 3.3–5 V · capacitive (no corrosion) · also reads soil temperature',
    notes: 'Push into the pot. Capacitive sensing lasts far longer than the cheap resistive probes.',
    source: ada('4026'), price: 7.5, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:soil-moisture'],
    requires: { bus: 'i2c', pins: 0, power: '3v3', currentMa: 5 },
    footprint: { w: 60, d: 20, h: 3, external: true },
    code: {
      micropython: { libraries: ['seesaw (adafruit_seesaw port)'], setup: 'from seesaw import Seesaw\nsoil = Seesaw(i2c, addr=0x36)', loop: 'moisture = soil.moisture_read()   # ~200 dry … ~2000 wet' },
      arduino: { libraries: ['Adafruit seesaw Library'], setup: '#include "Adafruit_seesaw.h"\nAdafruit_seesaw soil;\nsoil.begin(0x36);', loop: 'uint16_t moisture = soil.touchRead(0);' },
      python: { libraries: ['adafruit-circuitpython-seesaw'], setup: 'import board\nfrom adafruit_seesaw.seesaw import Seesaw\nsoil = Seesaw(board.I2C(), addr=0x36)', loop: 'moisture = soil.moisture_read()' },
    },
    tags: ['plant', 'garden', 'moisture'],
  },
  {
    id: 'loadcell-20kg', name: '20 kg load cell', category: 'Sensor',
    spec: 'Strain gauge bar · 4-wire · needs HX711 amplifier',
    notes: 'Turns the device into a scale. Mount between two plates; the planner adds the HX711 amplifier automatically.',
    source: ada('4543'), price: 3.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:weight'],
    requires: { pins: 0, power: '3v3', currentMa: 2, driver: 'drive:adc' },
    footprint: { w: 80, d: 13, h: 13, external: true },
    code: {
      micropython: { libraries: ['hx711'], setup: 'from hx711 import HX711\nscale = HX711(dout=Pin(HX_DOUT_PIN), pd_sck=Pin(HX_SCK_PIN))\nscale.tare()', loop: 'grams = scale.get_units()' },
      arduino: { libraries: ['HX711 Arduino Library'], setup: '#include "HX711.h"\nHX711 scale;\nscale.begin(HX_DOUT_PIN, HX_SCK_PIN);\nscale.tare();', loop: 'float grams = scale.get_units();' },
      python: { libraries: ['hx711'], setup: 'from hx711 import HX711\nscale = HX711(HX_DOUT_PIN, HX_SCK_PIN)', loop: 'grams = scale.get_weight_mean()' },
    },
    tags: ['scale', 'weight'],
  },
  {
    id: 'hx711', name: 'HX711 load cell amplifier', category: 'Driver',
    spec: '24-bit ADC · 2-wire clocked data · 3.3–5 V',
    notes: 'Required between any load cell and the controller. Added automatically with a load cell.',
    source: ada('5974'), price: 9.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['drive:adc'],
    requires: { bus: 'gpio', pins: 2, power: '3v3', currentMa: 2 },
    footprint: { w: 30, d: 22, h: 4 },
    tags: ['amplifier'],
  },
  {
    id: 'button', name: 'Momentary push button (panel mount)', category: 'Sensor',
    spec: '16 mm panel mount · normally open · fits a 16 mm hole in the enclosure',
    notes: 'One pin each, wired to ground with the controller pull-up enabled. The enclosure generator adds a hole per button.',
    source: ada('1445'), price: 0.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:button'],
    requires: { bus: 'gpio', pins: 1, currentMa: 0 },
    footprint: { w: 18, d: 18, h: 25 },
    code: {
      micropython: { libraries: [], setup: 'button = Pin(BUTTON_PIN, Pin.IN, Pin.PULL_UP)', loop: 'pressed = button.value() == 0' },
      arduino: { libraries: [], setup: 'pinMode(BUTTON_PIN, INPUT_PULLUP);', loop: 'bool pressed = digitalRead(BUTTON_PIN) == LOW;' },
      python: { libraries: ['gpiozero'], setup: 'button = Button(BUTTON_PIN)', loop: 'pressed = button.is_pressed' },
    },
    tags: ['input', 'button'],
  },
  {
    id: 'rotary', name: 'Rotary encoder with push switch', category: 'Sensor',
    spec: 'Quadrature · 24 detents · integrated push button',
    notes: 'A knob for menus and setpoints. Uses three GPIO pins.',
    source: ada('377'), price: 4.5, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['sense:rotary'],
    requires: { bus: 'gpio', pins: 3, currentMa: 0 },
    footprint: { w: 15, d: 15, h: 30 },
    code: {
      micropython: { libraries: ['rotary_irq_rp2 (micropython-rotary)'], setup: 'from rotary_irq_rp2 import RotaryIRQ\nknob = RotaryIRQ(pin_num_clk=ENC_A_PIN, pin_num_dt=ENC_B_PIN)', loop: 'position = knob.value()' },
      arduino: { libraries: ['Encoder'], setup: '#include <Encoder.h>\nEncoder knob(ENC_A_PIN, ENC_B_PIN);', loop: 'long position = knob.read();' },
      python: { libraries: ['gpiozero'], setup: 'knob = RotaryEncoder(ENC_A_PIN, ENC_B_PIN)', loop: 'position = knob.steps' },
    },
    tags: ['input', 'knob'],
  },

  // ───────────────────────── Actuators ─────────────────────────
  {
    id: 'servo-micro', name: 'Micro servo (SG92R class)', category: 'Actuator',
    spec: '180° · 5 V · ~1.5 kg·cm · PWM control · 23 × 12 × 29 mm',
    notes: 'Moves a small lever, flap, or dial. Powered from 5 V, controlled by one PWM pin. Never power servos from a 3.3 V pin.',
    source: ada('169'), price: 5.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['actuate:servo'],
    requires: { bus: 'pwm', pins: 1, power: '5v', currentMa: 250 },
    footprint: { w: 23, d: 12, h: 29 },
    code: {
      micropython: { libraries: [], setup: 'servo = PWM(Pin(SERVO_PIN)); servo.freq(50)\ndef servo_angle(deg): servo.duty_u16(int(1638 + deg / 180 * 6554))', loop: 'servo_angle(90)' },
      arduino: { libraries: ['Servo'], setup: '#include <Servo.h>\nServo servo;\nservo.attach(SERVO_PIN);', loop: 'servo.write(90);' },
      python: { libraries: ['gpiozero'], setup: 'servo = AngularServo(SERVO_PIN, min_angle=0, max_angle=180)', loop: 'servo.angle = 90' },
    },
    tags: ['servo', 'motion'],
  },
  {
    id: 'nema17', name: 'NEMA-17 stepper motor', category: 'Actuator',
    spec: '200 steps/rev · 12 V · 350 mA/phase · 42 mm frame',
    notes: 'Precise rotation for feeders, dosing, or positioning. Needs a stepper driver and a 12 V supply, both added automatically.',
    source: ada('324'), price: 14, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['actuate:stepper'],
    requires: { pins: 0, power: '12v', currentMa: 700, driver: 'drive:stepper' },
    footprint: { w: 42, d: 42, h: 40 },
    code: {
      micropython: { libraries: [], setup: 'step_pins = [Pin(p, Pin.OUT) for p in (STEP_A1_PIN, STEP_A2_PIN, STEP_B1_PIN, STEP_B2_PIN)]', loop: 'for i in range(200):\n    for j, p in enumerate(step_pins): p.value(1 if (i % 4) in ((j, (j + 1) % 4)) else 0)\n    time.sleep_ms(3)' },
      arduino: { libraries: ['Stepper'], setup: '#include <Stepper.h>\nStepper stepper(200, STEP_A1_PIN, STEP_A2_PIN, STEP_B1_PIN, STEP_B2_PIN);\nstepper.setSpeed(60);', loop: 'stepper.step(200);' },
    },
    tags: ['stepper', 'precise'],
  },
  {
    id: 'tt-motor', name: 'TT gearbox DC motor', category: 'Actuator',
    spec: '3–6 V · 200 rpm · 1:48 gearbox · common robot drive motor',
    notes: 'Spins a wheel or a simple mechanism. Needs an H-bridge driver, added automatically.',
    source: ada('3777'), price: 2.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['actuate:dc-motor'],
    requires: { pins: 0, power: '5v', currentMa: 250, driver: 'drive:dc-motor' },
    footprint: { w: 70, d: 22, h: 18 },
    code: {
      micropython: { libraries: [], setup: 'motor_in1 = PWM(Pin(MOTOR_IN1_PIN)); motor_in2 = Pin(MOTOR_IN2_PIN, Pin.OUT)', loop: 'motor_in2.value(0); motor_in1.duty_u16(30000)  # forward, ~45 %' },
      arduino: { libraries: [], setup: 'pinMode(MOTOR_IN1_PIN, OUTPUT); pinMode(MOTOR_IN2_PIN, OUTPUT);', loop: 'analogWrite(MOTOR_IN1_PIN, 120); digitalWrite(MOTOR_IN2_PIN, LOW);' },
      python: { libraries: ['gpiozero'], setup: 'motor = Motor(forward=MOTOR_IN1_PIN, backward=MOTOR_IN2_PIN)', loop: 'motor.forward(0.5)' },
    },
    tags: ['motor', 'wheel'],
  },
  {
    id: 'pump-peristaltic', name: 'Peristaltic liquid pump', category: 'Actuator',
    spec: '12 V DC · ~100 mL/min · silicone tubing · food-safe tubing path',
    notes: 'Moves a known amount of liquid per second of run time. Calibrate flow with a measuring cup. Driven by a MOSFET, added automatically.',
    source: ada('1150'), price: 24.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['actuate:pump'],
    requires: { pins: 0, power: '12v', currentMa: 300, driver: 'drive:mosfet' },
    footprint: { w: 70, d: 40, h: 34 },
    code: {
      micropython: { libraries: [], setup: 'pump = Pin(PUMP_PIN, Pin.OUT); pump.value(0)', loop: 'pump.value(1); time.sleep(seconds_for_dose); pump.value(0)' },
      arduino: { libraries: [], setup: 'pinMode(PUMP_PIN, OUTPUT); digitalWrite(PUMP_PIN, LOW);', loop: 'digitalWrite(PUMP_PIN, HIGH); delay(doseMs); digitalWrite(PUMP_PIN, LOW);' },
      python: { libraries: ['gpiozero'], setup: 'pump = OutputDevice(PUMP_PIN)', loop: 'pump.on(); time.sleep(seconds_for_dose); pump.off()' },
    },
    tags: ['pump', 'liquid', 'plant', 'dosing'],
  },
  {
    id: 'solenoid-12v', name: 'Push-pull solenoid 12 V', category: 'Actuator',
    spec: '12 V DC · ~10 mm stroke · intermittent duty',
    notes: 'A short linear push or pull, for latches and small presses. Not for continuous hold. MOSFET driver added automatically.',
    source: ada('412'), price: 7.5, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['actuate:solenoid'],
    requires: { pins: 0, power: '12v', currentMa: 650, driver: 'drive:mosfet' },
    footprint: { w: 30, d: 15, h: 15 },
    code: {
      micropython: { libraries: [], setup: 'solenoid = Pin(SOLENOID_PIN, Pin.OUT); solenoid.value(0)', loop: 'solenoid.value(1); time.sleep_ms(200); solenoid.value(0)' },
      arduino: { libraries: [], setup: 'pinMode(SOLENOID_PIN, OUTPUT);', loop: 'digitalWrite(SOLENOID_PIN, HIGH); delay(200); digitalWrite(SOLENOID_PIN, LOW);' },
      python: { libraries: ['gpiozero'], setup: 'solenoid = OutputDevice(SOLENOID_PIN)', loop: 'solenoid.on(); time.sleep(0.2); solenoid.off()' },
    },
    tags: ['solenoid', 'latch'],
  },
  {
    id: 'valve-12v', name: 'Plastic water solenoid valve 12 V', category: 'Actuator',
    spec: '12 V DC · 1/2" hose fittings · needs ≥ 0.02 MPa inlet pressure',
    notes: 'Opens a tap line for irrigation. Requires water pressure to close; will not work as a gravity drain. MOSFET driver added automatically.',
    source: ada('997'), price: 6.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['actuate:valve'],
    requires: { pins: 0, power: '12v', currentMa: 320, driver: 'drive:mosfet' },
    footprint: { w: 75, d: 40, h: 60, external: true },
    code: {
      micropython: { libraries: [], setup: 'valve = Pin(VALVE_PIN, Pin.OUT); valve.value(0)', loop: 'valve.value(1); time.sleep(open_seconds); valve.value(0)' },
      arduino: { libraries: [], setup: 'pinMode(VALVE_PIN, OUTPUT);', loop: 'digitalWrite(VALVE_PIN, HIGH); delay(openMs); digitalWrite(VALVE_PIN, LOW);' },
      python: { libraries: ['gpiozero'], setup: 'valve = OutputDevice(VALVE_PIN)', loop: 'valve.on(); time.sleep(open_seconds); valve.off()' },
    },
    tags: ['irrigation', 'water'],
  },
  {
    id: 'relay-stemma', name: 'Mini relay module (low voltage)', category: 'Actuator',
    spec: '3.3–5 V coil · switches up to 2 A at 30 V DC · JST PH',
    notes: 'Switches a separate low-voltage circuit on and off. Benchcraft does not support switching mains voltage; keep the load under 30 V DC.',
    source: ada('4409'), price: 6.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['actuate:relay'],
    requires: { bus: 'gpio', pins: 1, power: '3v3', currentMa: 60 },
    footprint: { w: 25, d: 20, h: 12 },
    code: {
      micropython: { libraries: [], setup: 'relay = Pin(RELAY_PIN, Pin.OUT); relay.value(0)', loop: 'relay.value(1)' },
      arduino: { libraries: [], setup: 'pinMode(RELAY_PIN, OUTPUT);', loop: 'digitalWrite(RELAY_PIN, HIGH);' },
      python: { libraries: ['gpiozero'], setup: 'relay = OutputDevice(RELAY_PIN)', loop: 'relay.on()' },
    },
    tags: ['switch', 'relay'],
  },
  {
    id: 'neopixel-1m', name: 'NeoPixel RGBW LED strip, 1 m (30 LEDs)', category: 'Actuator',
    spec: 'WS2812-class · 5 V · one data pin · up to ~1.8 A at full white',
    notes: 'Addressable colour lighting. Budget 60 mA per LED at full white; the planner adds a 5 V supply when needed.',
    source: ada('2836'), price: 14.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'low',
    provides: ['actuate:led-strip'],
    requires: { bus: 'gpio', pins: 1, power: '5v', currentMa: 1800 },
    footprint: { w: 1000, d: 12, h: 4, external: true },
    code: {
      micropython: { libraries: ['neopixel'], setup: 'import neopixel\nstrip = neopixel.NeoPixel(Pin(LED_PIN), 30, bpp=4)', loop: 'strip.fill((0, 40, 0, 0)); strip.write()' },
      arduino: { libraries: ['Adafruit NeoPixel'], setup: '#include <Adafruit_NeoPixel.h>\nAdafruit_NeoPixel strip(30, LED_PIN, NEO_GRBW + NEO_KHZ800);\nstrip.begin();', loop: 'strip.fill(strip.Color(0, 40, 0, 0)); strip.show();' },
      python: { libraries: ['adafruit-circuitpython-neopixel'], setup: 'import board, neopixel\nstrip = neopixel.NeoPixel(board.D18, 30, bpp=4)', loop: 'strip.fill((0, 40, 0, 0))' },
    },
    tags: ['light', 'rgb', 'ambient'],
  },
  {
    id: 'buzzer', name: 'Piezo buzzer 5 V', category: 'Actuator',
    spec: 'Active buzzer · 3–5 V · breadboard pins',
    notes: 'A simple beep for alerts and confirmations. One GPIO pin.',
    source: ada('1536'), price: 0.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'out-of-stock',
    alsoFrom: [generic('active-buzzer-5v')],
    provides: ['actuate:buzzer'],
    requires: { bus: 'gpio', pins: 1, power: '3v3', currentMa: 30 },
    footprint: { w: 12, d: 12, h: 9 },
    code: {
      micropython: { libraries: [], setup: 'buzzer = Pin(BUZZER_PIN, Pin.OUT)', loop: 'buzzer.value(1); time.sleep_ms(150); buzzer.value(0)' },
      arduino: { libraries: [], setup: 'pinMode(BUZZER_PIN, OUTPUT);', loop: 'digitalWrite(BUZZER_PIN, HIGH); delay(150); digitalWrite(BUZZER_PIN, LOW);' },
      python: { libraries: ['gpiozero'], setup: 'buzzer = Buzzer(BUZZER_PIN)', loop: 'buzzer.beep(0.15, 0.15, n=1)' },
    },
    tags: ['alert', 'sound'],
  },
  {
    id: 'fan-5v', name: 'Miniature 5 V cooling fan', category: 'Actuator',
    spec: '30 mm · 5 V · ~0.2 A · 2-wire',
    notes: 'Air movement for enclosures, small vents, or a desk gadget. Driven through a MOSFET so it can be switched or PWM-dimmed.',
    source: ada('3368'), price: 3.5, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['actuate:fan'],
    requires: { pins: 0, power: '5v', currentMa: 200, driver: 'drive:mosfet' },
    footprint: { w: 30, d: 30, h: 8 },
    code: {
      micropython: { libraries: [], setup: 'fan = PWM(Pin(FAN_PIN)); fan.freq(25_000); fan.duty_u16(0)', loop: 'fan.duty_u16(40000)' },
      arduino: { libraries: [], setup: 'pinMode(FAN_PIN, OUTPUT);', loop: 'analogWrite(FAN_PIN, 160);' },
      python: { libraries: ['gpiozero'], setup: 'fan = PWMOutputDevice(FAN_PIN)', loop: 'fan.value = 0.6' },
    },
    tags: ['fan', 'cooling'],
  },

  // ───────────────────────── Drivers ─────────────────────────
  {
    id: 'mosfet-n', name: 'N-channel power MOSFET (IRLB8721)', category: 'Driver',
    spec: 'Logic-level gate · 30 V · 16 A · TO-220',
    notes: 'Low-side switch for pumps, solenoids, fans, and 12 V loads. Add a flyback diode across inductive loads and a 100 kΩ gate pull-down.',
    source: ada('355'), alsoFrom: [generic('irlz44n')],
    price: 2.25, pricing: 'live', priceCheckedAt: CHECKED, stock: 'out-of-stock',
    provides: ['drive:mosfet'],
    requires: { bus: 'gpio', pins: 1, currentMa: 0 },
    footprint: { w: 10, d: 5, h: 16 },
    tags: ['switch', 'low-side'],
  },
  {
    id: 'tb6612', name: 'TB6612 dual motor driver', category: 'Driver',
    spec: 'Dual H-bridge · 1.2 A per channel · 4.5–13.5 V motor supply · 3.3–5 V logic',
    notes: 'Drives two DC motors or one bipolar stepper. Far cooler-running than the old L298.',
    source: ada('2448'), price: 6.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['drive:dc-motor', 'drive:stepper'],
    requires: { bus: 'gpio', pins: 3, currentMa: 0 },
    footprint: { w: 20, d: 20, h: 8 },
    tags: ['h-bridge', 'stepper'],
  },

  // ───────────────────────── Displays ─────────────────────────
  {
    id: 'oled-128x64', name: '1.3" OLED 128×64 (SSD1306)', category: 'Display',
    spec: 'I2C · 3.3–5 V · monochrome · STEMMA QT',
    notes: 'Shows a few lines of text or a small graph. Readable in the dark; no backlight needed.',
    source: ada('938'), price: 19.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['display:text', 'display:graphic'],
    requires: { bus: 'i2c', pins: 0, power: '3v3', currentMa: 20 },
    footprint: { w: 35, d: 33, h: 5 },
    code: {
      micropython: { libraries: ['ssd1306'], setup: 'import ssd1306\nscreen = ssd1306.SSD1306_I2C(128, 64, i2c)', loop: 'screen.fill(0); screen.text(status_line, 0, 0); screen.show()' },
      arduino: { libraries: ['Adafruit SSD1306', 'Adafruit GFX Library'], setup: '#include <Adafruit_SSD1306.h>\nAdafruit_SSD1306 screen(128, 64, &Wire);\nscreen.begin(SSD1306_SWITCHCAPVCC, 0x3D);', loop: 'screen.clearDisplay(); screen.setCursor(0,0); screen.print(statusLine); screen.display();' },
      python: { libraries: ['adafruit-circuitpython-ssd1306'], setup: 'import board, adafruit_ssd1306\nscreen = adafruit_ssd1306.SSD1306_I2C(128, 64, board.I2C())', loop: 'screen.fill(0); screen.text(status_line, 0, 0, 1); screen.show()' },
    },
    tags: ['screen', 'oled'],
  },
  {
    id: 'lcd-16x2', name: '16×2 character LCD', category: 'Display',
    spec: 'Parallel · 5 V · white on blue · 80 × 36 mm',
    notes: 'Large, cheap, readable text. Uses six GPIO pins and 5 V; the OLED is a better fit for 3.3 V boards.',
    source: ada('1447'), price: 10.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['display:text'],
    requires: { bus: 'gpio', pins: 6, power: '5v', currentMa: 30 },
    footprint: { w: 80, d: 36, h: 12 },
    code: {
      arduino: { libraries: ['LiquidCrystal'], setup: '#include <LiquidCrystal.h>\nLiquidCrystal lcd(LCD_RS, LCD_EN, LCD_D4, LCD_D5, LCD_D6, LCD_D7);\nlcd.begin(16, 2);', loop: 'lcd.setCursor(0, 0); lcd.print(statusLine);' },
    },
    tags: ['screen', 'lcd', '5v'],
  },

  // ───────────────────────── Power ─────────────────────────
  {
    id: 'psu-5v-2a5', name: '5 V 2.5 A USB power supply', category: 'Power',
    spec: 'Wall adapter · micro-USB cable · regulated',
    notes: 'Powers the controller and 5 V peripherals from the wall.',
    source: ada('1995'), price: 8.25, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['power:5v'], supplies: { rail: '5v', currentMa: 2500 },
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 0, d: 0, h: 0, external: true },
    tags: ['wall', 'usb'],
  },
  {
    id: 'psu-12v-5a', name: '12 V 5 A switching power supply', category: 'Power',
    spec: 'Wall adapter · 2.1 mm barrel · regulated',
    notes: 'Powers pumps, solenoids, steppers, and 12 V loads. Pair with a buck converter to feed the controller from the same brick.',
    source: ada('352'), price: 24.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['power:12v'], supplies: { rail: '12v', currentMa: 5000 },
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 0, d: 0, h: 0, external: true },
    tags: ['wall', '12v'],
  },
  {
    id: 'buck-5v', name: 'MPM3610 5 V buck converter', category: 'Power',
    spec: '6–21 V in · 5 V 1.2 A out · tiny breakout',
    notes: 'Makes a clean 5 V rail from the 12 V supply so one wall adapter powers everything.',
    source: ada('4739'), price: 6.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['power:5v'], supplies: { rail: '5v', currentMa: 1200 },
    requires: { pins: 0, power: '12v', currentMa: 0 },
    footprint: { w: 18, d: 18, h: 5 },
    tags: ['regulator'],
  },
  {
    id: 'lipo-1200', name: 'LiPo battery 3.7 V 1200 mAh', category: 'Power',
    spec: 'JST-PH 2-pin · protection circuit · 62 × 34 × 5 mm',
    notes: 'Portable power for a day or more of low-duty sensing. Pair with a charger board or an ESP32-S3 Feather.',
    source: ada('258'), price: 9.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['power:battery'], supplies: { rail: '3v3', currentMa: 1000 },
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 62, d: 34, h: 5 },
    tags: ['battery', 'portable'],
  },
  {
    id: 'lipo-charger', name: 'Micro-LiPo USB charger', category: 'Power',
    spec: 'Charges 3.7 V LiPo at 100/500 mA · micro-USB',
    notes: 'Needed to recharge the LiPo unless the controller has a charger on board.',
    source: ada('1904'), price: 6.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['power:charger'],
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 20, d: 20, h: 5 },
    tags: ['charger'],
  },

  // ───────────────────────── Mechanical / assembly ─────────────────────────
  {
    id: 'breadboard-half', name: 'Half-size breadboard', category: 'Assembly',
    spec: '400 tie points · 82 × 55 mm',
    notes: 'Solder-free assembly. The enclosure is sized to hold it when the design uses one.',
    source: ada('64'), price: 4.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'low',
    provides: ['mech:prototyping'],
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 82, d: 55, h: 10 },
    tags: ['solderless'],
  },
  {
    id: 'jumpers', name: 'Jumper wires, male–male ×20', category: 'Assembly',
    spec: '150 mm · breadboard pitch',
    notes: 'Enough for one small build. Get female–female too if a breakout has headers soldered.',
    source: ada('1957'), price: 1.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['mech:wiring'],
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 0, d: 0, h: 0, external: true },
    tags: ['wire'],
  },
  {
    id: 'stemma-cable', name: 'STEMMA QT / Qwiic cable 100 mm', category: 'Assembly',
    spec: 'JST SH 4-pin · plug-and-play I2C',
    notes: 'Connects any STEMMA QT sensor without soldering. One per I2C board.',
    source: ada('4210'), price: 0.95, pricing: 'live', priceCheckedAt: CHECKED, stock: 'in-stock',
    provides: ['mech:wiring'],
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 0, d: 0, h: 0, external: true },
    tags: ['i2c', 'solderless'],
  },
  {
    id: 'enclosure-printed', name: 'Printed enclosure (PLA)', category: 'Mechanical',
    spec: 'Generated OpenSCAD box + lid · sized to the parts list · ~40–90 g PLA',
    notes: 'Fabricated on a connected 3D printer or downloaded as STL. Material allowance only.',
    source: generic('pla-enclosure'), price: 3, pricing: 'estimate', priceCheckedAt: CHECKED, stock: 'unknown',
    provides: ['mech:enclosure'],
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 0, d: 0, h: 0, external: true },
    tags: ['3d-print', 'case'],
  },
  {
    id: 'm3-hardware', name: 'M3 screws, nuts and standoffs kit', category: 'Mechanical',
    spec: 'Nylon or steel · assorted lengths',
    notes: 'Mounts boards to the printed enclosure standoffs.',
    source: generic('m3-standoff-kit'), price: 6, pricing: 'estimate', priceCheckedAt: CHECKED, stock: 'unknown',
    provides: ['mech:mounting'],
    requires: { pins: 0, currentMa: 0 },
    footprint: { w: 0, d: 0, h: 0, external: true },
    tags: ['screws'],
  },
]
