import { z } from 'zod';
export const recipeIds = ['dispenser','logger','cycler'] as const;
export type RecipeId = typeof recipeIds[number];
export const recipes = {
 dispenser:{name:'Liquid dispenser',title:'Timed liquid dispenser',description:'Repeatable doses for filling, sampling, and small-batch production.',category:'Fluid handling',unit:'mL',input:'Start / stop buttons',output:'12 V dosing pump',accent:'#55d9bd'},
 logger:{name:'Temperature logger',title:'Bench temperature logger',description:'Record temperature over serial for process checks and experiments.',category:'Measurement',unit:'°C',input:'DS18B20 probe',output:'Serial data log',accent:'#7baaff'},
 cycler:{name:'Cycle tester',title:'Actuator cycle tester',description:'Repeat on/off cycles to exercise a low-voltage test fixture.',category:'Test & validation',unit:'cycles',input:'Start / stop buttons',output:'12 V test load',accent:'#c5a0ff'}
};
export const configSchema = z.object({volume:z.number().min(1).max(1000),flow:z.number().min(1).max(5000),timeout:z.number().min(1).max(300),interval:z.number().min(1).max(3600),cycles:z.number().int().min(1).max(10000),onTime:z.number().min(.1).max(60),offTime:z.number().min(.1).max(60)}).strict();
export const projectInput = z.object({id:z.string().uuid(),name:z.string().trim().min(1).max(90),prompt:z.string().max(2000),recipe:z.enum(recipeIds),config:configSchema,checked:z.array(z.number().int().min(0).max(5)).max(6),notes:z.string().max(4000)}).strict();
export type Project = z.infer<typeof projectInput> & {updatedAt?:string};
export const defaults = {volume:100,flow:120,timeout:90,interval:5,cycles:50,onTime:2,offTime:3};
export function projectId(){ const bytes=crypto.getRandomValues(new Uint8Array(16)); bytes[6]=(bytes[6]&15)|64; bytes[8]=(bytes[8]&63)|128; const h=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`; }
export function draft(recipe:RecipeId='dispenser'):Project{return {id:projectId(),name:recipes[recipe].title,prompt:'',recipe,config:{...defaults},checked:[],notes:''};}
export type Part = {id:string;name:string;category:string;spec:string;price:number;notes:string};
export const catalogue:Part[] = [
 {id:'esp32',name:'ESP32 development board',category:'Controller',spec:'ESP32-WROOM · 3.3 V logic · USB power',price:12,notes:'Choose a classic ESP32 board exposing GPIO 4, 18, 25, 26, and 27. Verify the exact board pinout.'},
 {id:'pump',name:'Peristaltic dosing pump',category:'Actuator',spec:'12 V DC · calibrate flow under load',price:24,notes:'Planning placeholder; select a SKU and check startup / stall current and wetted materials.'},
 {id:'driver',name:'Protected MOSFET driver',category:'Driver',spec:'3.3 V logic input · 12 V load',price:9,notes:'Must have a flyback path, input pull-down, and current rating above load stall current. A bare GPIO cannot power a motor.'},
 {id:'supply',name:'12 V DC power supply',category:'Power',spec:'External regulated supply',price:15,notes:'Size after measuring / checking load current. Power ESP32 separately via USB; never connect 12 V to a GPIO.'},
 {id:'tube',name:'Pump tubing & fittings',category:'Mechanical',spec:'Matched to selected pump head',price:8,notes:'Check bore, chemical compatibility, and pressure rating for the actual fluid.'},
 {id:'buttons',name:'Start / stop button pair',category:'Input',spec:'Normally open · logic-level contacts',price:5,notes:'Start on GPIO 25, stop on GPIO 26; both to ground with internal pull-ups.'},
 {id:'probe',name:'DS18B20 temperature probe',category:'Sensor',spec:'1-Wire · 3.3 V · 4.7 kΩ pull-up',price:8,notes:'Use powered three-wire mode. Pull data to 3.3 V and verify wire assignment with the supplier.'},
 {id:'load',name:'12 V fixture test load',category:'Actuator',spec:'User-selected solenoid or actuator',price:20,notes:'Placeholder only. Continuous duty, travel limits, and stall current require review for your fixture.'},
 {id:'wires',name:'Wire & terminal set',category:'Assembly',spec:'Logic wiring + rated load conductors',price:7,notes:'Select conductor gauge and terminals for actual current; share the logic ground at the driver.'},
 {id:'fuse',name:'Fuse & disconnect',category:'Power',spec:'Series with 12 V load supply',price:6,notes:'Select fuse and disconnect ratings for the actual load. This is independent of firmware stop.'},
 {id:'tray',name:'Printed electronics tray',category:'Mechanical',spec:'120 × 90 × 18 mm concept',price:4,notes:'Material cost allowance. Parametric OpenSCAD concept requires fit and thermal review.'},
 {id:'usb',name:'USB data cable',category:'Connection',spec:'Matches your ESP32 board connector',price:4,notes:'Use a data-capable cable for firmware flashing and serial logging.'}
];
export function partsFor(recipe:RecipeId){const ids=recipe==='logger'?['esp32','probe','wires','tray','usb']:['esp32',recipe==='dispenser'?'pump':'load','driver','supply',...(recipe==='dispenser'?['tube']:[]),'buttons','wires','fuse','tray','usb'];return ids.map(id=>catalogue.find(p=>p.id===id)!);}
export function cost(recipe:RecipeId){return partsFor(recipe).reduce((s,p)=>s+p.price,0);}
export function checks(p:Project){const c=p.config;const seconds=c.volume/c.flow*60;return [
 {title:'Supported controller',detail:'Classic ESP32, 3.3 V signal interface.',ok:true},
 {title:p.recipe==='dispenser'?'Dose fits cutoff':p.recipe==='cycler'?'Cycle timing in range':'Sampling interval in range',detail:p.recipe==='dispenser'?`${seconds.toFixed(1)} s estimated dose / ${c.timeout} s cutoff`:p.recipe==='cycler'?`${c.cycles} cycles · ${(c.cycles*(c.onTime+c.offTime)/60).toFixed(1)} min total`:`One sample every ${c.interval} seconds`,ok:p.recipe!=='dispenser'||seconds<=c.timeout},
 {title:'Physical build review',detail:'Confirm exact part ratings, connections, and enclosure fit.',ok:null},
 {title:p.recipe==='dispenser'?'Flow calibration':p.recipe==='logger'?'Sensor calibration':'Fixture verification',detail:'Requires measurements on your assembled device.',ok:null}
 ];}
export const testSteps = ['Confirm the exact board pinout and component ratings.','Inspect wiring and check power polarity with the load disconnected.','Compile firmware and verify output-off behavior after boot.','Test start, stop, and fault behavior using an LED or disconnected load.','Measure actual performance and record results below.','Repeat the acceptance test and review before unattended operation.'];
export function wiring(recipe:RecipeId){return recipe==='logger'?[['ESP32 3V3','Probe VDD','Sensor power'],['ESP32 GND','Probe GND','Common reference'],['ESP32 GPIO 4','Probe DQ','4.7 kΩ pull-up from DQ to 3V3'],['USB','Laptop','Power + 115200 baud serial']]:[['ESP32 GPIO 18','Driver IN','3.3 V control; active high'],['ESP32 GND','Driver GND / supply −','Shared reference'],['12 V supply +','Fuse → disconnect → load +','Select ratings for actual load'],['Load −','Driver switched output','Use protected low-side driver'],['GPIO 25 / GPIO 26','Start / stop → GND','Internal pull-ups enabled'],['USB','ESP32','Separate board power; no 12 V to board']];}
export function firmware(p:Project){const c=p.config;if(p.recipe==='logger')return `// Benchcraft: classic ESP32 temperature logger — review before use\n// Install OneWire and DallasTemperature through Arduino Library Manager.\n#include <OneWire.h>\n#include <DallasTemperature.h>\nOneWire bus(4);\nDallasTemperature probe(&bus);\nconst unsigned long SAMPLE_MS = ${Math.round(c.interval*1000)}UL;\nunsigned long lastSample = 0;\nvoid setup() { Serial.begin(115200); probe.begin(); Serial.println("time_ms,temperature_C,status"); }\nvoid loop() {\n  if (millis() - lastSample < SAMPLE_MS) return;\n  lastSample = millis(); probe.requestTemperatures();\n  float t = probe.getTempCByIndex(0);\n  Serial.print(millis()); Serial.print(",");\n  if (t == DEVICE_DISCONNECTED_C) Serial.println("nan,DISCONNECTED");\n  else { Serial.print(t, 2); Serial.println(",OK"); }\n}\n`;
return `// Benchcraft: ${recipes[p.recipe].name} — classic ESP32\n// PROTOTYPE: compile and test on an LED before connecting a load.\n// Active-high protected driver on GPIO18; hardware input pull-down required.\n// GPIO25 START and GPIO26 STOP connect to GND.\n// Serial commands: s=start, x=stop. No automatic restart after boot or stop.\nconst bool DRY_RUN = true; // Change ONLY after reviewing the physical build.\nconst int OUTPUT_PIN=18, START_PIN=25, STOP_PIN=26;\nconst unsigned long ON_MS=${Math.round((p.recipe==='dispenser'?Math.min(c.volume/c.flow*60,c.timeout):c.onTime)*1000)}UL;\nconst unsigned long OFF_MS=${Math.round(c.offTime*1000)}UL;\nconst unsigned long MAX_CYCLES=${p.recipe==='dispenser'?1:c.cycles}UL;\nbool running=false, phaseOn=false, lastStart=false;\nunsigned long changedAt=0, completed=0, lastPress=0;\nvoid output(bool on) {\n  digitalWrite(OUTPUT_PIN, (!DRY_RUN && on) ? HIGH : LOW);\n  Serial.println(on ? "REQUEST_ON" : "OUTPUT_OFF");\n}\nvoid stopRun() { running=false; phaseOn=false; output(false); }\nvoid setup() {\n  digitalWrite(OUTPUT_PIN,LOW); pinMode(OUTPUT_PIN,OUTPUT);\n  pinMode(START_PIN,INPUT_PULLUP); pinMode(STOP_PIN,INPUT_PULLUP);\n  Serial.begin(115200); stopRun();\n  Serial.println(DRY_RUN ? "DRY_RUN_READY" : "READY");\n}\nvoid loop() {\n  unsigned long now=millis();\n  bool pressed=digitalRead(START_PIN)==LOW;\n  bool edge=pressed && !lastStart; lastStart=pressed;\n  char command=Serial.available()?Serial.read():0;\n  if(digitalRead(STOP_PIN)==LOW || command=='x'){ stopRun(); return; }\n  if(!running && (command=='s' || (edge && now-lastPress>200))){\n    lastPress=now; completed=0; running=true; phaseOn=true; changedAt=now; output(true);\n  }\n  if(!running) return;\n  if(phaseOn && now-changedAt>=ON_MS){\n    output(false); phaseOn=false; changedAt=now; completed++;\n    if(completed>=MAX_CYCLES){stopRun(); Serial.println("COMPLETE");}\n  }else if(!phaseOn && now-changedAt>=OFF_MS){\n    phaseOn=true; changedAt=now; output(true);\n  }\n}\n`;}
export function scad(){return `// Benchcraft concept tray. Units: mm. Fit-check before printing.\n// No board-specific hole pattern; use insulated mounts after measurement.\nwidth=120; depth=90; height=18; wall=3;\ndifference(){\n cube([width,depth,height]);\n translate([wall,wall,wall]) cube([width-2*wall,depth-2*wall,height]);\n translate([width/2-10,-1,8]) cube([20,wall+2,12]);\n}\n`;}
export function planMarkdown(p:Project){return `# ${p.name}\n\nBenchcraft preliminary build plan · ${new Date().toISOString().slice(0,10)}\n\n## Task\n${p.prompt||recipes[p.recipe].description}\n\nRecipe: ${recipes[p.recipe].name}. Physical hardware has not been validated.\n\n## Configuration\n${JSON.stringify(p.config,null,2)}\n\n## Parts — budget estimates, not supplier quotes\n${partsFor(p.recipe).map(x=>`- ${x.name}: $${x.price}. ${x.spec}. ${x.notes}`).join('\n')}\n\nEstimated parts total: $${cost(p.recipe)}. Excludes tax, shipping, tooling, and labor.\n\n## Connections\n${wiring(p.recipe).map(x=>`- ${x[0]} → ${x[1]}: ${x[2]}`).join('\n')}\n\n## Design checks\n${checks(p).map(x=>`- ${x.title}: ${x.ok===true?'Rule passed':x.ok===false?'Revise configuration':'Needs physical review'}. ${x.detail}`).join('\n')}\n\n## Acceptance checklist\n${testSteps.map((x,i)=>`- [${p.checked.includes(i)?'x':' '}] ${x}`).join('\n')}\n\n## Test notes\n${p.notes||'No measured results recorded.'}\n\n## Firmware\n\`\`\`cpp\n${firmware(p)}\`\`\`\n\n## Enclosure concept\n\`\`\`scad\n${scad()}\`\`\`\n`;}
export function matchPrompt(prompt:string):{recipe:RecipeId;config:typeof defaults;recognized:boolean}{const s=prompt.toLowerCase();const recipe:RecipeId=/temperature|thermal|logger|sensor/.test(s)?'logger':/cycl|actuator|solenoid|fixture/.test(s)?'cycler':'dispenser';const config={...defaults};const volume=s.match(/(\d+(?:\.\d+)?)\s*(?:ml|millilit)/);const cycles=s.match(/(\d+)\s*cycles/);const interval=s.match(/every\s+(\d+(?:\.\d+)?)\s*s/);if(volume)config.volume=Math.min(1000,Math.max(1,Number(volume[1])));if(cycles)config.cycles=Math.min(10000,Math.max(1,Number(cycles[1])));if(interval)config.interval=Math.min(3600,Math.max(1,Number(interval[1])));return {recipe,config,recognized:/dispens|pump|fill|dos|temperature|thermal|logger|sensor|cycl|actuator|solenoid|fixture/.test(s)};}
