import assert from 'node:assert/strict';
import {defaults,draft,checks,configSchema,projectInput,matchPrompt,partsFor,firmware,planMarkdown} from '../lib/bench.ts';
const p=draft();
assert.equal(checks(p)[1].ok,true);
assert.match(checks(p)[1].detail,/50.0 s/);
p.config={...defaults,volume:1000,timeout:30};
assert.equal(checks(p)[1].ok,false,'Dose exceeding cutoff must fail');
assert.equal(configSchema.safeParse({...defaults,flow:0}).success,false);
assert.equal(configSchema.safeParse({...defaults,cycles:1.5}).success,false);
assert.equal(configSchema.safeParse({...defaults,unknown:1}).success,false);
assert.equal(projectInput.safeParse({...p,name:''}).success,false);
assert.equal(matchPrompt('Log temperature every 10 seconds').recipe,'logger');
assert.equal(matchPrompt('Log temperature every 10 seconds').config.interval,10);
assert.equal(matchPrompt('Run 120 cycles').config.cycles,120);
assert.equal(matchPrompt('Dispense 250 ml').config.volume,250);
assert.equal(matchPrompt('Build a radio telescope').recognized,false);
assert.equal(new Set(partsFor('dispenser').map(p=>p.id)).size,partsFor('dispenser').length);
assert.match(firmware(p),/const bool DRY_RUN = true/);
assert.match(firmware(p),/const unsigned long ON_MS=30000UL/);
assert.match(planMarkdown(p),/Physical hardware has not been validated/);
assert.match(firmware(draft('logger')),/DEVICE_DISCONNECTED_C/);
console.log('Domain checks passed: recipe extraction, constraints, cutoff, exports, and firmware defaults.');
